#!/usr/bin/env node
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const d = join(dirname(fileURLToPath(import.meta.url)), '.');
let pass = 0, fail = 0;
const ok = (label, cond) => { if (cond) { pass++; console.log('  OK ' + label); } else { fail++; console.log('  FAIL ' + label); } };
console.log('');
console.log('======== updater tests ========');
console.log('');
const manifest = readFileSync(join(d, 'update-protected.txt'), 'utf8');
ok('protects reports/', manifest.includes('reports/'));
ok('protects evidence/', manifest.includes('evidence/'));
ok('negates .env.example', manifest.includes('!.env.example'));
const src = readFileSync(join(d, 'update.mjs'), 'utf8');
ok('maps --dry-run', src.includes("case '--dry-run'") && src.includes("return ['-DryRun']"));
ok('maps --hard', src.includes("case '--hard'") && src.includes("return ['-Hard']"));
const ps1 = readFileSync(join(d, 'update.ps1'), 'utf8');
ok('powershell dry-run guard', ps1.includes('if ($DryRun)'));
ok('powershell hard reset opt-in', ps1.includes('if ($Hard)'));
const sh = readFileSync(join(d, 'update.sh'), 'utf8');
ok('bash dry-run before git init', sh.indexOf('if [[ ""$DRY_RUN"" -eq 1 ]]') < sh.indexOf('git init'));
ok('bash negation support', sh.includes('apply_negation_patterns'));
ok('bash failure trap', sh.includes('trap on_err ERR'));
const readme = readFileSync(join(d, '..', 'README.md'), 'utf8');
ok('documents update:dry', readme.includes('npm run update:dry'));
ok('documents update:hard opt-in', readme.includes('npm run update:hard'));
console.log('');
console.log('======== ' + (fail === 0 ? 'ALL PASS' : fail + ' FAILED') + ' ========');
console.log('');
process.exit(fail === 0 ? 0 : 1);
